### ISSUE TITLE
Two funcitons in m6A QTL mapping

### ISSUE THREAD

**Issue by zhangpicb** [scottzijiezhang/MeRIPtools#11]
Dear authors,

Thanks for the awesome codes for the beautiful figures.

I read the paper about m6A QTLs for 60YRIs.And I want to learn how to find m6A QTLs.
When I read learn the code in https://scottzijiezhang.github.io/m6AQTL_reproducibleDocument/m6AQTL_mapping.html, I find 2 function get_peak_logOR() and extractIP() are not defined.Do these 2 function in MeRIPtools package or other packages?

Thanks in advanced.

**Comment by kevinlkx** [comment]
Thanks for your interest. Sorry for the late reply. Yes, those two functions were from the MeRIPtools package. But it seems the get_peak_logOR() function is not included in the current release version of MeRIPtools. We will update the MeRIPtools  package and let you know once it is ready.

**Comment by zhangpicb** [comment]
Thanks!

**Comment by kevinlkx** [comment]
We have included the get_peak_logOR() function in the package. Thanks!
