### ISSUE TITLE
callPeakFisher result is too simple

### ISSUE THREAD

**Issue by gnilihzeux** [scottzijiezhang/MeRIPtools#2]
Dear author,
  Although `callPeakFisher` has call peaks out, the results is too simple for a flexible analysis.
  Could you offer the corresponding more context such as p value ?

**Comment by scottzijiezhang** [comment]
Hi Jinwen, 

The peak calling function we implemented in MeRIPtools is mainly to define testing windows, in which we draw read counts for further quantitative analysis. 

The reason we don't report p-value is that we design it for calling peaks in multiple samples and we don't have a good way of combining p values from different samples. There are other packages such as exomePeak that merged reads from all samples to call peak and report p-values. 

Thanks
Zijie

**Comment by gnilihzeux** [comment]
Thanks for your reply.
I think it's better to store the results with **p-value** and **oddRatio** of `callPeakFisher` for a flexible choice.
